name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  p80ts:
    name: 8.0ts
    runs-on: windows-latest 
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.0'
            extensions: memcached
          env:
            phpts: ts # specify ts or nts
  p80nts:
    name: 8.0nts
    runs-on: windows-latest
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.0'
            extensions: memcached

  p74ts:
    name: 7.4ts
    runs-on: windows-latest 
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'
            extensions: memcached
          env:
            phpts: ts # specify ts or nts
  p74nts:
    name: 7.4nts
    runs-on: windows-latest
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.0'
            extensions: memcached
  p73ts:
    name: 7.3ts
    runs-on: windows-latest
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.3'
            extensions: memcached
          env:
            phpts: ts # specify ts or nts
  p73nts:
    name: 7.3nts
    runs-on: windows-latest
    steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.3'
            extensions: memcached
