name: Build and Test on Windows
on: 
  push: 
   
env: 
    Ver: windows_msgpack_support
    Mg: 2.2.0RC1
    Ig: 3.2.7
    Pg: 3.2.0
jobs:
  ts74-x64-msgpack:
    defaults:
      run:
        shell: powershell
    runs-on: windows-2019
    strategy:
      matrix:
          version: ["8.0"]
          arch: [x64]
          ts: [ts,nts]
          ext: ["basic","igbinary","msgpack"]
    steps:
      - name: vc15
        if: matrix.version=='7.4'
        run: |
          echo "Vs=vc15" >> $env:GITHUB_ENV
      - name: vs16
        if: matrix.version!='7.4'
        run: |
         echo "Vs=vs16" >> $env:GITHUB_ENV
      - name: Setup PHP
        id: setup-php
        uses: cmb69/setup-php-sdk@v0.6
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
          deps: zlib,zip,libxml,libiconv,libjpeg,edit,libssl,libzip
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name : show deps
        shell: cmd
        run: |
          dir /N /S ..\deps
          
      - name: get php source and deps
        run: |
          php-sdk/phpsdk-${{env.Vs}}-${{matrix.arch}}.bat
          phpsdk_buildtree.bat ${{matrix.version}}-${{matrix.arch}}
          echo "copy cmdb deps to phpsource deps"
          xcopy /S /E ..\deps ${{matrix.version}}-${{matrix.arch}}\${{env.Vs}}\${{matrix.arch}}\deps
          echo "get latest php version"
          curl   https://windows.php.net/downloads/releases/releases.json -o r.json
          $CLRJson = Get-Content -Raw -Path "r.json" | ConvertFrom-Json
          $version = $CLRJson."${{matrix.version}}".version 
          rm r.json
          cd ${{matrix.version}}-${{matrix.arch}}/${{env.Vs}}/${{matrix.arch}}
          echo "get latest php source code"
          curl  https://windows.php.net/downloads/releases/php-$version-src.zip -o ${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}-${{matrix.ext}}.zip
          7z x ${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}-${{matrix.ext}}.zip 
          rm ${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}-${{matrix.ext}}.zip
          cd php-$version-src
          echo "get memcached dependency"
          curl https://github.com/lifenglsf/libmemcached-window-dll-lib/blob/main/${{matrix.arch}}.zip?raw=true -o ${{matrix.arch}}.zip  
          7z x ${{matrix.arch}}.zip -odeps
          xcopy /S /E /Y deps ..\deps
          rm ${{matrix.arch}}.zip
          dir
          remove-item .\deps -Recurse
          echo "get memcached ext source code"
          curl  https://github.com/lifenglsf/php-memcached/archive/refs/heads/windows_msgpack_support.zip -o m.zip
          7z x m.zip 
          xcopy /S /E /Y php-memcached-windows_msgpack_support ..\deps\include
          md .\ext\memcached
          xcopy /S /E /Y php-memcached-windows_msgpack_support ext\memcached
          rm m.zip
          remove-item .\php-memcached-windows_msgpack_support -Recurse
          if("${{matrix.ext}}" -eq "basic"){
            .\buildconf.bat
            if("${{matrix.ts}}" -eq "nts"){
            .\configure --enable-memcached=shared --enable-memcached-session --enable-memcached-json --with-php-build=..\deps --disable-zts
            }else{
            .\configure --enable-memcached=shared --enable-memcached-session --enable-memcached-json --with-php-build=..\deps
            }
            
          }
          if("${{matrix.ext}}" -eq "msgpack"){
           curl   https://github.com/msgpack/msgpack-php/archive/refs/heads/master.zip -o msgpack.zip
           7z x msgpack.zip 
           xcopy /S /E /Y msgpack-php-master ..\deps\include
           md .\ext\msgpack
           xcopy /S /E /Y msgpack-php-master .\ext\msgpack
           remove-item .\msgpack-php-master -Recurse

           .\buildconf.bat
           if("${{matrix.ts}}" -eq "nts"){
                .\configure --enable-memcached=shared --enable-memcached-session --enable-memcached-json --enable-memcached-msgpack --enable-msgpack=shared --with-php-build=..\deps --disable-zts

           }else{
              .\configure --enable-memcached=shared --enable-memcached-session --enable-memcached-json --enable-memcached-msgpack --enable-msgpack=shared --with-php-build=..\deps
           }
          }
          if("${{matrix.ext}}" -eq "igbinary"){
           curl   https://github.com/igbinary/igbinary/archive/refs/heads/master.zip -o igbinary.zip
           7z x igbinary.zip
           xcopy /S /E /Y igbinary-master ..\deps\include
           md .\ext\igbinary
           xcopy /S /E /Y igbinary-master .\ext\igbinary
           remove-item .\igbinary-master -Recurse
           .\buildconf.bat
           if("${{matrix.ts}}" -eq "nts"){
              .\configure --enable-memcached=shared --enable-memcached-session --enable-memcached-json --enable-memcached-igbinary --enable-igbinary=shared --with-php-build=..\deps --disable-zts

           }else{
               .\configure --enable-memcached=shared --enable-memcached-session --enable-memcached-json --enable-memcached-igbinary --enable-igbinary=shared --with-php-build=..\deps
          }
          }
          dir ext\memcached
          nmake
          mkdir -p ${{github.workspace}}\${{env.Pg}}-${{matrix.ext}}-php${{matrix.version}}-${{matrix.ts}}_${{matrix.arch}}
          copy ..\deps\bin\libmemcached.dll ${{github.workspace}}\${{env.Pg}}-${{matrix.ext}}-php${{matrix.version}}-${{matrix.ts}}_${{matrix.arch}}
          if('${{matrix.arch}}' -eq 'x86'){
            if('${{matrix.ts}}' -eq 'nts'){
              copy Release\php_memcached.dll ${{github.workspace}}\${{env.Pg}}-${{matrix.ext}}-php${{matrix.version}}-${{matrix.ts}}_${{matrix.arch}}
            }else{
              copy Release_TS\php_memcached.dll ${{github.workspace}}\${{env.Pg}}-${{matrix.ext}}-php${{matrix.version}}-${{matrix.ts}}_${{matrix.arch}}
            }
          }else{
            if('${{matrix.ts}}' -eq 'nts'){
              copy x64\Release\php_memcached.dll ${{github.workspace}}\${{env.Pg}}-${{matrix.ext}}-php${{matrix.version}}-${{matrix.ts}}_${{matrix.arch}}
            }else{
              copy x64\Release_TS\php_memcached.dll ${{github.workspace}}\${{env.Pg}}-${{matrix.ext}}-php${{matrix.version}}-${{matrix.ts}}_${{matrix.arch}}
            }
          }
          dir
          7z a ${{github.workspace}}\${{env.Pg}}-${{matrix.ext}}-php${{matrix.version}}-${{matrix.ts}}_${{matrix.arch}}.7z ${{github.workspace}}\${{env.Pg}}-${{matrix.ext}}-php${{matrix.version}}-${{matrix.ts}}_${{matrix.arch}}\*.*
      - name: Accidentally upload to the same artifact via multiple jobs
        uses: actions/upload-artifact@v3
        with:
            name: ${{env.Pg}}-${{matrix.ext}}-php${{matrix.version}}-${{matrix.ts}}_${{matrix.arch}}
            path: ${{ github.workspace }}\${{env.Pg}}-${{matrix.ext}}-php${{matrix.version}}-${{matrix.ts}}_${{matrix.arch}}.7z
  create_release:
    needs: [ts74-x64-msgpack]
    defaults:
      run:
        shell: cmd
    runs-on: windows-2019
    steps: 
      - name: prepare release
        shell: powershell
        run: |
          $version="8.0"
          $arch="x64"
          $ts="ts","nts"
          $ext="basic","igbinary","msgpack"
          $filepath=@()
          $workspace = @()
          Foreach($v in $version){
            Foreach($a in $arch){
              Foreach($t in $ts){
                Foreach($e in $ext){
                  $tmp=-join("${{env.Pg}}","-",$e,"-","php",$v,"-",$t,"_",$a)
                  $filepath+=$tmp
                  $workspace+="${{ github.workspace }}"
                }
              }
            }
          }
          $rpath=$filepath -join " "
          $wpath=$workspace -join " "
          echo "Release_path=$rpath" >> $env:GITHUB_ENV
          echo "Workspace_path=$wpath" >> $env:GITHUB_ENV
      - name : download artifact
        uses: marcofaggian/action-download-multiple-artifacts@v3.0.7
        with:
          names: ${{env.Release_path}}
          paths: ${{env.Workspace_path}}
      - name: test
        shell: powershell
        run: |
          dir
          Get-ChildItem -Path ${{ github.workspace }} -Filter *.7z | Foreach-Object {
            echo $_.name;
            $dir = $_.name -replace "-","\"
            $dir = $dir -replace ".7z",""
            $oname=$_.name -replace ".7z",""
            echo "oname:$oname"
            mkdir -p $dir
            7z x $_.name
            copy $oname\*.dll $dir
          }
          Get-ChildItem -Path ${{ github.workspace }} -recurse

#      - name: make release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "${{env.release_path}}"
#          token: ${{ secrets.GITHUB_TOKEN }}
#          tag: v${{env.Pg}}-auto
#      - name: nmake
#        run: |
#          nmake
#       - name: Checkout memcached
#         uses: actions/checkout@v3
#         with:
#           repository: lifenglsf/php-memcached
#           ref: ${{ env.ver }}
#       - name: Setup PHP
#         id: setup-php
#         uses: cmb69/setup-php-sdk@v0.3
#         with:
#           version: ${{matrix.version}}
#           arch: ${{matrix.arch}}
#           ts: ${{matrix.ts}}
#           deps: zlib
#       - name: Download deps
#         run: |
#           curl -L https://github.com/lifenglsf/libmemcached-window-dll-lib/blob/main/${{matrix.arch}}.zip?raw=true -o ${{matrix.arch}}.zip
#           7z x ${{matrix.arch}}.zip -o..\deps
#           echo "stable version ${{ env.ver }}"
#           curl -L https://github.com/msgpack/msgpack-php/archive/refs/heads/master.zip -o msgpack.zip
#           7z x msgpack.zip -o.\
#           xcopy /S /E msgpack-php-master ..\deps\include
#           md.\ext\msgpack
#           xcopy /S /E msgpack-php-master .\ext\msgpack
#           dir ext /N /S
#           curl -L https://windows.php.net/downloads/pecl/releases/msgpack/${{env.Mg}}/php_msgpack-${{env.Mg}}-${{matrix.version}}-${{matrix.ts}}-${{env.Vs}}-${{matrix.arch}}.zip -o msgpack-php.zip
#           7z x msgpack-php.zip -o.\msgpack_dll
#           copy msgpack_dll\php_msgpack.dll ${{steps.setup-php.outputs.prefix}}\ext
          
#       - name: Enable Developer Command Prompt
#         uses: ilammy/msvc-dev-cmd@v1
#         with:
#           arch: ${{matrix.arch}}
#           toolset: ${{steps.setup-php.outputs.toolset}}
#       - name: phpize
#         run: |
#           phpize
#       - name: configure
#         run: |
#           configure --enable-memcached=shared --enable-memcached-session --enable-memcached-json --enable-memcached-msgpack --enable-msgpack=shared --with-php-build=..\deps --with-prefix=${{steps.setup-php.outputs.prefix}} --with-config-file-path=${{steps.setup-php.outputs.prefix}}
#       - name: make
#         run: nmake
#       - name: make install
#         run: nmake install
#       - name: copy ini
#         run: copy ${{steps.setup-php.outputs.prefix}}\php.ini-development ${{steps.setup-php.outputs.prefix}}\php.ini
#       - name: copy libmemcached 
#         run:  copy ..\deps\bin\libmemcached.dll ${{steps.setup-php.outputs.prefix}}
#       - name: set extension dir
#         run : echo extension_dir="${{steps.setup-php.outputs.prefix}}\ext"; >>${{steps.setup-php.outputs.prefix}}\php.ini
#       - name: show file
#         run: dir ${{steps.setup-php.outputs.prefix}} /N /S
#       - name: extension path
#         run: php -i|grep "extension_dir"
#       - name: add memcached msgpack ext
#         run : |
#           echo extension=msgpack; >>${{steps.setup-php.outputs.prefix}}\php.ini
#           echo extension=memcached; >>${{steps.setup-php.outputs.prefix}}\php.ini
#       - name: show ini config
#         run: php --ini
#       - name: php module
#         run: php -m
#       - name: copy file
#         run: |
#           mkdir -p ${{github.workspace}}\php-${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}
#           copy ..\deps\bin\libmemcached.dll ${{ github.workspace }}\php-${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}
#           copy ${{steps.setup-php.outputs.prefix}}\ext\php_memcached.dll ${{ github.workspace }}\php-${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}
#           dir ${{ github.workspace }} /N /S
#           7z a ${{ github.workspace }}\php-${{ env.Ver }}-${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}.7z ${{ github.workspace }}\php-${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}\*.*
          
#       #- name: test
#       #  run: nmake test
#       # - name: Accidentally upload to the same artifact via multiple jobs
#       #  uses: actions/upload-artifact@v3
#       #  with:
#       #      name: php-${{ env.Ver }}-${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}
#       #      path: ${{ github.workspace }}\php-${{ env.Ver }}-${{matrix.version}}-${{matrix.arch}}-${{matrix.ts}}.7z
#   create_tag:   
#     needs: [ts74-x64-msgpack]
#     defaults:
#       run:
#         shell: cmd
#     runs-on: windows-2019
#     steps: 
#       - name : download artifact
#         uses: marcofaggian/action-download-multiple-artifacts@v3.0.7
#         with:
#           names: php-${{ env.Ver }}-7.4-x64-ts php-${{ env.Ver }}-8.0-x64-ts php-${{ env.Ver }}-8.1-x64-ts php-${{ env.Ver }}-7.4-x64-nts php-${{ env.Ver }}-8.0-x64-nts php-${{ env.Ver }}-8.1-x64-nts php-${{ env.Ver }}-7.4-x86-nts php-${{ env.Ver }}-8.0-x86-nts php-${{ env.Ver }}-8.1-x86-nts php-${{ env.Ver }}-7.4-x86-ts php-${{ env.Ver }}-8.0-x86-ts php-${{ env.Ver }}-8.1-x86-ts
#           paths: ${{ github.workspace }} ${{ github.workspace }} ${{ github.workspace }} ${{ github.workspace }} ${{ github.workspace }} ${{ github.workspace }} ${{ github.workspace }} ${{ github.workspace }} ${{ github.workspace }} ${{ github.workspace }} ${{ github.workspace }} ${{ github.workspace }}
#       #- name: delete_tag
#       #  uses: dev-drprasad/delete-tag-and-release@v0.2.0
#       #  with:
#       #    delete_release: true # default: false
#       #    tag_name: ${{ env.Ver }} # tag name to delete
#       #  env:
#       #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       #- name: create release
#       #  uses: ncipollo/release-action@v1
#       #  with:
#       #    artifacts: "${{github.workspace}}\\php-${{ env.Ver }}-7.4-x64-ts.7z,${{github.workspace}}\\php-${{ env.Ver }}-8.0-x64-ts.7z,${{github.workspace}}\\php-${{ env.Ver }}-8.1-x64-ts.7z,${{github.workspace}}\\php-${{ env.Ver }}-7.4-x64-nts.7z,${{github.workspace}}\\php-${{ env.Ver }}-8.0-x64-nts.7z,${{github.workspace}}\\php-${{ env.Ver }}-8.1-x64-nts.7z,${{github.workspace}}\\php-${{ env.Ver }}-7.4-x86-ts.7z,${{github.workspace}}\\php-${{ env.Ver }}-8.0-x86-ts.7z,${{github.workspace}}\\php-${{ env.Ver }}-8.1-x86-ts.7z,${{github.workspace}}\\php-${{ env.Ver }}-7.4-x86-nts.7z,${{github.workspace}}\\php-${{ env.Ver }}-8.0-x86-nts.7z,${{github.workspace}}\\php-${{ env.Ver }}-8.1-x86-nts.7z"
#       #    token: ${{ secrets.GITHUB_TOKEN }}
#       #    tag: ${{ env.Ver }}
